# Generated by Django 4.2.29 on 2026-03-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrationdata',
            name='drop_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hydrationdata',
            name='drop_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hydrationdata',
            name='fill_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hydrationdata',
            name='fill_time',
            field=models.FloatField(default=0),
        ),
    ]
