# Generated by Django 4.2.29 on 2026-03-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hydrationdata_drop_amount_hydrationdata_drop_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrationdata',
            name='drop_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hydrationdata',
            name='fill_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hydrationdata',
            name='total_dropped',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hydrationdata',
            name='total_filled',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hydrationdata',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hydrationdata',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
