# Generated by Django 4.2.29 on 2026-05-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hydrationdata_drop_count_hydrationdata_fill_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrationdata',
            name='device_id',
            field=models.CharField(default='bottle_01', max_length=50),
        ),
        migrations.AlterField(
            model_name='hydrationdata',
            name='event',
            field=models.CharField(choices=[('DRINK', 'Drink'), ('FILL', 'Fill'), ('DROP', 'Drop'), ('NORMAL', 'Normal')], max_length=10),
        ),
    ]
