# Generated by Django 4.2.29 on 2026-05-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hydrationdata_device_id_alter_hydrationdata_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrationdata',
            name='alert',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hydrationdata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
