# Generated by Django 4.2.29 on 2026-05-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_hydrationdata_alert_alter_hydrationdata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrationdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
