# Generated by Codex on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_hydrationdata_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrationdata',
            name='water_ml',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hydrationdata',
            name='balance_ml',
            field=models.FloatField(default=0),
        ),
    ]
