# Generated by Codex on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_hydrationdata_water_ml_balance_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrationdata',
            name='direction',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hydrationdata',
            name='pitch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hydrationdata',
            name='roll',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hydrationdata',
            name='raw_current_dist',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hydrationdata',
            name='corrected_current_dist',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hydrationdata',
            name='water_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hydrationdata',
            name='raw_empty_dist',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hydrationdata',
            name='distance_offset',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hydrationdata',
            name='empty_dist',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
