# Generated by Codex on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_hydrationdata_debug_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrationdata',
            name='calibration_points_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hydrationdata',
            name='reminder_interval_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hydrationdata',
            name='last_drink_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hydrationdata',
            name='next_reminder_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hydrationdata',
            name='drop_latch_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hydrationdata',
            name='drop_latch_direction',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
