# Generated by Codex on 2026-05-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_hydrationdata_reminder_drop_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrationdata',
            name='event_amount',
            field=models.FloatField(default=0),
        ),
    ]
