# Generated by Django 4.2.29 on 2026-05-31 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_parentpushtoken_notificationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_reminder', models.BooleanField(default=True)),
                ('behind_goal', models.BooleanField(default=True)),
                ('low_water', models.BooleanField(default=True)),
                ('bottle_empty', models.BooleanField(default=True)),
                ('drop_detected', models.BooleanField(default=True)),
                ('extreme_heat', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_start', models.CharField(default='21:00', max_length=5)),
                ('quiet_end', models.CharField(default='06:00', max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
